### ISSUE TITLE
스터디 회고

### ISSUE THREAD

**Issue by jongmin92** [quick-starters/design-pattern#1]

**Comment by evan-hwang** [comment]
K
- 좋은 책 선정이 스터디 기간 내내 긍정적으로 작용했다.

P
- 

T
- 책 내용 단순 요약이 아닌 확장을 해보자.

**Comment by MoonJiHyun** [comment]
[Keep] 
- 개념과 함께 간단한 예제 프로그래밍을 작성해보는게 더 학습이 잘 되었다.
- 개념을 쉽게 풀어서 설명해줘서 훨씬 이해가 잘 되었다 (시각적인 도표도 한몫한듯)

[Problem] 
- 개인적으로 여유가 없었던 시기라서 다소 아쉬웠다

[Try]
- 다음에도 동일하게 예제 프로그래밍이나 간단한 학습 프로그램을 만들면서 하면 좋을듯

**Comment by jongmin92** [comment]
- K
  - 책이 쉽고 재밌어서 끝까지 진행하는 것에 문제가 없었다.
  - 챕터 별로 분량이 크게 차이나지 않아서 부담이 없었다.
  - 디자인 패턴의 주제가 연차가 조금 쌓이고 다시 접하니 흥미로웠다.
- P
  - X
- T
  - 책의 내용을 더 확장할 수 없을지.
